### ISSUE TITLE
Furst connection error

### ISSUE THREAD

**Issue by lukino87** [fra589/cn5X#11]
both firmware and software are at the latest version the error message occurs only during the first connection. starting first the serial monitor of arduino ide then its software instead the whole connects and works without any error.

**Comment by cneve** [comment]
It is true that the first connection needs to be connected through a serial port monitor, and then cn5X can connect. So do I. @lukino87 @fra589

**Comment by fra589** [comment]
Hello @lukino87, @cneve,  
This is strange !?!?!? Are you both on Windows ?  
In my home, it work fine from first connection, but usualy,  I use Debian Linux.  
Can you activate the debug tab of cn5X before connecting and post the whole debug output from the begining to the timeout message please ?  
@++;  
Gauthier.

**Comment by lukino87** [comment]
hello and thanks again for your work and your help yes I'm on windows 10 64 as soon as I get home I will make you have the debug thanks again

**Comment by fra589** [comment]
..No more info for debug... Issue closed.
