### ISSUE TITLE
Jogging

### ISSUE THREAD

**Issue by liushuya7** [fra589/cn5X#2]
Hi @fra589,

Is there a way to adjust the jogging speed in cn5x?
<img width="295" alt="qwe" src="https://user-images.githubusercontent.com/6867028/39543737-116ab73e-4e1a-11e8-9c37-a6e28b4a9f8a.png">
screenshot from Laserweb

Thanks,
Joshua

**Comment by fra589** [comment]
Hi @liushuya7,

This functionality is not yet developped. Jogging actualy use one speed for all moves, this speed is defined in line 35 of cn5X_config.py

@++;
Gauthier.

**Comment by liushuya7** [comment]
Got it. Thanks! Look forward to having it being added on.

**Comment by fra589** [comment]
Functionality added to release 0.3 published today :  
https://github.com/fra589/cn5X/releases/tag/v0.3-alpha
I hope this help you,
@ += 1
Gauthier.

**Comment by liushuya7** [comment]
Great! Thanks!

**Comment by cneve** [comment]
Can the 0.3 version run on Debian?
