### ISSUE TITLE
Missing a G92 button..

### ISSUE THREAD

**Issue by spiderdab** [fra589/cn5X#20]
Hi, I found this grbl controller very useful, easy to read and stable. (I have problem both with UGS and bCNC, under PopOs!)
One thing that I'm missing is a Button to send a "G92 X0 Y0 Z0" like a "Set Zero", maybe with the possibility to fill 3 textfields if you want to set a position different from Zero..
Is this something you can add?
Thank you.

p.s. I'm running a double X gantry, with your grbl-mega-x5 firmware.

**Comment by fra589** [comment]
Hi @spiderdab,  
  
This is a good question!
cn5X ++ is still in development, and the functionality you request is planned.
I unfortunately don't have enough time for the moment to do everything I hope to do, I think to be able to move this subject forward next winter...  
  
In the meantime, it is possible to use zero offsets G54 to G59 using the context menu with the right mouse button on the display of the working positions:  
![cn5X-local-menu](https://user-images.githubusercontent.com/19529154/91477514-bce7b500-e89e-11ea-8965-5ce44283ff53.png)  
This send 'G10 L2 P- ...' gCode sentence to set the active G54, G55, ... or G59 coordinate system.  
  
@++;  
Gauthier.

**Comment by spiderdab** [comment]
Thanks for answering. I didn't know about the right-click context menù.
You already did a great job.

**Comment by fra589** [comment]
Hi all,  
  
G92 features have been added in addition to the G54-59 features in the today's new version 0.8.  
See in the Machine menu.

@++;
Gauthier.
