### ISSUE TITLE
cnc5X on Debian

### ISSUE THREAD

**Issue by BosniaCNC** [fra589/cn5X#22]
Help to run the program on Linux (Debian-9).
Thank you very much!

**Comment by fra589** [comment]
Hi @BosniaCNC,  
  
cn5X++ is developped under Debian, so, it's very easy to use it on another Debian
  
1) Install prerequisites:  
`apt-get install python3 python3-pyqt5 python3-pyqt5.qtserialport`  
2) Add the user to the unix group "dialout":  
`adduser <username> dialout`  
3) Download or clone cn5X and put it where you want on your system, ensure that the file cn5X.py is executable or make it executable:
`cd <cn5X_directory>; chmod +x cn5X.py`  
4) Run cn5X:
`cd <cn5X_directory>; ./cn5X.py`  

![Capture_cn5X01](https://user-images.githubusercontent.com/19529154/94782982-54738280-03cc-11eb-9540-7ea8b267064a.PNG)

5) In the "**Port**" drop down list, chose the port where Grbl is connected, then click on the "**Connect**" button,  
6) Go to the "**Machine/Grbl configuration**" menu to adjust your Grbl parameters  
   or Double click on the "**Emergency stop**" button to unlock it and begin to use your CNC.  

@++;  
Gauthier.

**Comment by BosniaCNC** [comment]
Thanks for the detailed instruction!
