### ISSUE TITLE
Windows conection problem

### ISSUE THREAD

**Issue by fus3** [fra589/cn5X#23]
Hello i just installed cn5x on windows and when i connect to the mega2560 i get this message Imatge1 . I found a issue on grbl-master5x github that had the same problem on another version and he find a solution sending Ctrl + X trough arduino ide and then it works but in my case this isnt working, i also tried to edit the line 254 of the grblComSerial.py but it also didn't work. here you have another imatges of version, debug ,etc. Tell me what to do. Im in windows 10 32 bit
![3](https://user-images.githubusercontent.com/75036029/100257681-7c9fdd80-2f46-11eb-99ea-97914f65d000.PNG)
![4](https://user-images.githubusercontent.com/75036029/100257704-83c6eb80-2f46-11eb-92b8-320e0b8b7af6.PNG)
![captura 1](https://user-images.githubusercontent.com/75036029/100257706-845f8200-2f46-11eb-9ea0-6022f1ca6726.PNG)
![Captura 2](https://user-images.githubusercontent.com/75036029/100257707-84f81880-2f46-11eb-8fde-b8d0844ead4a.PNG)

**Comment by fra589** [comment]
Hi @fus3,  
  
This is the same issue than this one: [#19](https://github.com/fra589/cn5X/issues/19).  
As [I already say here](https://github.com/fra589/cn5X/issues/19#issuecomment-658303521), I need to rewrite the serial communication module without the qserial QT5 python object wich don't work as expected in Windows.  
It will be done soon, but sure, I am late on this subject, and also on many others... :confused: :smirk:  
  
Watch [the #19 issue](https://github.com/fra589/cn5X/issues/19) for the future correction, I close this one.  

@++;  
Gauthier.
