### ISSUE TITLE
large gcode files?

### ISSUE THREAD

**Issue by viewsat** [fra589/cn5X#29]
cn5X cannot use large gcode files?

**Comment by fra589** [comment]
Hello,

> "When searching for bugs, there is never a too precise description." - Confucius |D

I am not a diviner and I do not see what can be my contribution to answering your question which I find far too imprecise...

Despite everything, the education I received in my youth (hello, please, thank you, goodbye, ...) still allows me politeness, so I greet you. And if one happens to me next time to understand a precise question, asked with tangible elements allowing its study (what is the version of the application, on which operating system, what is the error message produced by the application, by the system or observed behavior of the application, exact operating condition, how to reproduce the error, file which poses problem, what is the definition of large file, parameters, ... in short, all the details which will put me on the way) I will be happy to try to correct your problem.

Regards,
@++;
Gauthier.
