### ISSUE TITLE
cn5x++ not work

### ISSUE THREAD

**Issue by hzxiaoyu** [fra589/cn5X#3]
Hi, @fra589 
My win10 opened it, and it can connect to mega2560,shows:
Grbl 1.1f ['$' for help]
[MSG:'$H'|'$X' to unlock]
[VER:1.1f.20170802:]
[N_AXIS=5]
[OPT:VNM,35,255]
ok$$

2018-06-25 17:19:39 : Info    : grblCom: Starting grblComSerial thread.
2018-06-25 17:19:39 : Info    : grblComSerial running "grblComSerial" from thread #0xc64.
2018-06-25 17:19:39 : Info    : grblComSerial: comPort COM3 open, RC = True
2018-06-25 17:19:40 : Info    : cn5X ++: Grbl initialized.
2018-06-25 17:23:37 : Info    : on_btnPausePooling(True)

And debug shows:
<<< <Alarm|MPos:0.000,0.000,0.000,0.000,0.000|Bf:35,255|FS:0,0|WCO:5.000,5.000,0.000,0.000,0.000>
>>> ?
<<< <Alarm|MPos:0.000,0.000,0.000,0.000,0.000|Bf:35,255|FS:0,0|Ov:100,100,100>
I can't send $x because the frame and send button is grey 

What is wrong?

**Comment by fra589** [comment]
Hi, @hzxiaoyu 
It is strange...  
I have had a same problem in old, but not published, version, and I had it corrected...  
I don't remember exactly what was the problem, but it was an intermittent problem which disappeared after turning Grbl off and on.  
Unfortunately I am on a business trip and I can not test to find and fix right now, I would be back home around mid-July, I would look at it when I return.  
Sorry for the correction delay,  
@ += 1  
Gauthier.  

P.S. : By the way, it seem that you have'nt the last grbl-Mega-5X version (1.1g.20180423)... Somes bugs and typos have been corrected from your version.

**Comment by hzxiaoyu** [comment]
@fra589 I just updated 1.1g20180423,but it is the same problem...

**Comment by fra589** [comment]
@hzxiaoyu, OK, I will see this ASAP... Please, be patient :-)

**Comment by hzxiaoyu** [comment]
@fra589 OK，now it works. thank you .
How about make keyboard control the axis like UGS? 
And do you know in grbl ,how to use probe function?

**Comment by fra589** [comment]
Hi @hzxiaoyu,  
Keyboard control is in TODO list, but with low priority. The main goal of cn5X++ is to make CNC controler usable on Raspberry or equivalent with a touch screen.  
Personaly, I don't use the probe function for the moment. Probe pin is defined in cpu_map.h as MEGA2560 Analog Pin 15.  
@ += 1  
Gauthier.
