### ISSUE TITLE
Fonctionne t'il avec un arduino et un tb6560 sur port LPT?

### ISSUE THREAD

**Issue by theck32** [fra589/cn5X#40]
j'ai un tb6560 4 axe avec port db25 (LPT) cela fonctionne t'il avec mon tb6560 sur le port db25 à arduino pour pouvoir l'utiliser sur port usb? merci ce module tb6560 4 axe sur cette photo :
![images (4)](https://user-images.githubusercontent.com/17702421/165224004-09dd551c-02fb-4b2e-a674-1c3f6bbc7728.jpeg)

**Comment by fra589** [comment]
Bonjour,  
  
cn5X communique avec le logiciel Grbl de l’Arduino, cela n'a aucun rapport avec la partie matérielle qu'il y à derrière l'Arduino pour conduire les moteurs pas à pas.  
Donc, je ne vois pas ce qui pourrait ne pas fonctionner en raison de la carte tb6560 à partir du moment ou elle est correctement gérée par Grbl.
cn5X est développé conjointement avec ma version grbl-Mega-5X pour permettre de profiter de toutes ses fonctionnalités, notamment au delà de 3 axes. Avec les autres version de Grbl, seulement 3 axes seront gérés.  
  
@++;  
Gauthier.
