### ISSUE TITLE
homing direction invert mask crash

### ISSUE THREAD

**Issue by wbendick** [fra589/cn5X#42]
Upon attempting to save a new homing direction invert mask, cn5X crashed with the error:

Traceback (most recent call last):
  File "/Users/will/cn5X/grblConfig.py", line 567, in on_Apply
    self.sig_config_changed.emit("$23=".format(self.__di.emHomeDirInvert.value()))
TypeError: 'int' object is not callable
Abort trap: 6

**Comment by fra589** [comment]
Hi @wbendick, 

I just published version v0.8.9.20230418 to fix this bug.
Please, test and report.

@++;
Gauthier.

**Comment by fra589** [comment]
No news for a week... Assuming fix is OK => Issue closed.
