### ISSUE TITLE
hi，about linux_cn5X._v0.3

### ISSUE THREAD

**Issue by cneve** [fra589/cn5X#6]
Can the 0.3 version run on Debian?

**Comment by fra589** [comment]
Hi @cneve,

cn5X is written under Debian.

Dependency :  
apt-get install python3 python3-pyqt5 python3-pyqt5.qtserialport

The user need to be member of dialout  group :  
adduser <username> dialout

@++;
Gauthier.

**Comment by cneve** [comment]
Thank you very much Gauthier. I've run cn5X version 3.0 successfully on Windows 32bit. I'll continue to specialize in your project. Thank you.
